#' Read Depth Table
#' 
#' This function calculates sensitivity outcomes for a specified range of read depths.
#' @param vaf_threshold Decimal minimum variant allele frequency threshold.
#' @param expected_vaf Decimal expected variant allele frequency.
#' @param minimum_depth Minimum read depth to calculate probability matrix. Defaults to 0.
#' @param maximum_depth Maximum read depth to calculate probability matrix. Defaults to 3000.
#' @param min_alt_reads Minimum alternate supporting reads to call the variant. Defaults to 2.

read_depth_table <- function(vaf_threshold, 
                             expected_vaf,
                             minimum_depth=0,
                             maximum_depth=3000,
                             min_alt_reads=2,
                             sensitivity_goal=0.999,
                             ...){
  depth_odds <- data.frame(read_depth=minimum_depth:maximum_depth)
  depth_odds$min_alt_reads <- ceiling(depth_odds$read_depth*vaf_threshold)
  depth_odds$min_alt_reads[(depth_odds$min_alt_reads <= min_alt_reads)] <- min_alt_reads
  depth_odds$prob=1-pbinom(depth_odds$min_alt_reads, 
                           depth_odds$read_depth, expected_vaf)
  return(depth_odds)
}

#' Calculate Required Depth
#' 
#' This function returns a required read depth to achieve desired sensitivity.
#' @param read_depth_table Probability matrix of read depths. Can be generated by read_depth_table().
#' @param sensitivity_goal Decimal sensitivity goal for the target panel.

calculate_required_depth <- function(read_depth_table,
                                    sensitivity_goal, ...){
  required_depth <- min(dplyr::filter(read_depth_table, prob > sensitivity_goal)$read_depth)
  return(required_depth)
}

#' Read Depth Plot
#' 
#' This is the core plot function for comparing minimal depth to current depth.
#' @param read_depth_table Probability matrix of read depths. Can be generated by read_depth_table().
#' @param sensitivity_goal Decimal sensitivity goal for the target panel.
#' @param required_depth Minimum read depth requirement for sensitivity goal. Can be generated by calculate_required_depth().
#' @param minimum_depth Minimum read depth to calculate probability matrix. Defaults to 0.
#' @param maximum_depth Maximum read depth to calculate probability matrix. Defaults to 3000.

read_depth_plot = function(
  read_depth_table, sensitivity_goal, required_depth, minimum_depth=10, maximum_depth=3000, ...){
  
  ggplot(data=read_depth_table, aes(x=read_depth, y=prob)) + 
    geom_smooth(method='lm', formula = y ~ poly(x, 5)) +
    theme_bw() +
    theme(text = element_text(size=20)) +
    theme(axis.text.x = element_text(angle=90, hjust=1)) +
    ggtitle("Sensitivity at Read Depth") +
    geom_hline(yintercept=sensitivity_goal, linetype=2) +
    geom_vline(xintercept=required_depth, linetype=2) +
    annotate("text", label=paste('Minimum', as.character(required_depth)), x=required_depth, y=0.95, angle=90, size=10) +
    scale_y_continuous("Sensitivity", limits=c(0.9, 1)) +
    scale_x_log10("Paired Read Depth", limits=c(minimum_depth, max(c(read_depth_table$read_depth, required_depth))), 
                  breaks=c(10, 20, 50, 100, 200, 500, 1000, minimum_depth)) 
}

#' Plot Minimal Depth
#' 
#' Master plotting function that combines all package utilities to generate a 
#' plot of minimum vs. current read depths.
#' @param vaf_threshold Decimal minimum variant allele frequency threshold.
#' @param expected_vaf Decimal expected variant allele frequency. Defaults to germline heterozygous (0.5).
#' @param minimum_depth Minimum read depth to calculate probability matrix. Defaults to 0.
#' @param maximum_depth Maximum read depth to calculate probability matrix. Defaults to 3000.
#' @param min_alt_reads Minimum alternate supporting reads to call the variant. Defaults to 2.
#' @param sensitivity_goal Decimal sensitivity goal for the target panel. Defaults to 0.999 (99.9%).

plot_minimal_depth <- function(vaf_threshold, 
                               expected_vaf=0.5,
                               minimum_depth=1,
                               maximum_depth=3000,
                               min_alt_reads=2,
                               sensitivity_goal=0.999){
  params <- c(as.list(environment()))
  read_depth_table <- do.call(read_depth_table, params)
  required_depth <- calculate_required_depth(read_depth_table, sensitivity_goal)
  read_depth_plot(read_depth_table, sensitivity_goal, required_depth)
}
